name: Build Updater
on:
  workflow_dispatch:
  push:
    tags:
      - '**' # 监听所有 tag 事件
  pull_request:
concurrency:
  group: build_xl-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ contains(github.ref, 'refs/tags/') && 'Release Build' || 'CI Build' }}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Nuget Packages
        run: dotnet restore -p:RestoreUseStaticGraphEvaluation=true

      - name: Define VERSION
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          @(
              $env:GITHUB_REPOSITORY.Split('/')[-1]
              $env:GITHUB_REF -replace '.*/'
              $env:GITHUB_SHA.Substring(0,7)
          ) | Set-Content -Path VERSION

      - name: Build Solution
        shell: pwsh
        run: |
          $msbuild = (Resolve-Path "${env:ProgramFiles}\Microsoft Visual Studio\*\*\MSBuild\Current\Bin\MSBuild.exe").Path
          & "$msbuild" "$env:GITHUB_WORKSPACE/Dalamud.Updater.sln" /t:Build /p:Configuration=Release

      - name: Handle Artifacts
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: Updater-artifact
          path: Dalamud.Updater/bin/Release/net48/
          retention-days: 1

      - name: Create Release Package
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        shell: pwsh
        run: |
          Write-Host "Create Zip package"
          $srcDir = Join-Path $env:GITHUB_WORKSPACE "Dalamud.Updater\bin\Release\net48"
          Compress-Archive -Path "$srcDir/*.*" -DestinationPath ./Dalamud.Updater.zip -Force

      - name: Publish Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./Dalamud.Updater.zip
          name: Release ${{ github.ref_name }}
          prerelease: true
