name: Build Updater
on:
  workflow_dispatch:
  push:
  pull_request:
concurrency: 
  group: build_xl-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    name: Build Release on Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Restore Nuget Packages
        run: dotnet restore -p:RestoreUseStaticGraphEvaluation=true

      - name: Define VERSION
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          @(
              $env:GITHUB_REPOSITORY.Split('/')[-1]
              $env:GITHUB_REF -replace '.*/'
              $env:GITHUB_SHA.Substring(0,7)
          ) | Set-Content -Path VERSION

      - name: Build DotNet4 for Release
        shell: pwsh
        run: |
          $msbuild = (Resolve-Path "${env:ProgramFiles}\Microsoft Visual Studio\*\*\MSBuild\Current\Bin\MSBuild.exe").Path
          & "$msbuild" "$env:GITHUB_WORKSPACE/Dalamud.Updater.sln" /t:Build /p:Configuration=Release

      - name: Create package
        shell: pwsh
        run: |
          $src = Join-Path $env:GITHUB_WORKSPACE "Dalamud.Updater\bin\Release\net48\Dalamud.Updater.exe"
          Compress-Archive -Path $src -DestinationPath ./release.zip -Force

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./release.zip
          name: Release ${{ github.ref_name }}
          prerelease: true

  build:
    name: Build on Windows
    runs-on: windows-2022
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Restore Nuget Packages
        run: dotnet restore -p:RestoreUseStaticGraphEvaluation=true

      - name: Define VERSION
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          @(
              $env:GITHUB_REPOSITORY.Split('/')[-1]
              $env:GITHUB_REF -replace '.*/'
              $env:GITHUB_SHA.Substring(0,7)
          ) | Set-Content -Path VERSION

      - name: Build DotNet4 Master
        shell: pwsh
        run: |
          $msbuild = (Resolve-Path "${env:ProgramFiles}\Microsoft Visual Studio\*\*\MSBuild\Current\Bin\MSBuild.exe").Path
          & "$msbuild" "$env:GITHUB_WORKSPACE/Dalamud.Updater.sln" /t:Build /p:Configuration=Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Updater-artifact
          path: Dalamud.Updater/bin/Release/net48/
          retention-days: 1
